//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco.Infrastructure.DataPersistent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIOS
    {
        public int USU_ID_USUARIO { get; set; }
        public string USU_USUARIO { get; set; }
        public string USU_PASSWORD { get; set; }
        public string USU_ROL_ADMINISTRADOR { get; set; }
        public string USU_ESTATUS { get; set; }
        public Nullable<System.DateTime> USU_FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> USU_FECHA_CAMBIO_PASSWORD { get; set; }
        public Nullable<int> USU_CANTIDAD_LOGIN_ERROR { get; set; }
        public Nullable<bool> USU_FLAG_ACTIVO { get; set; }
    }
}
